config/routes.rb
Rails.application.routes.draw do
  
  # get 'mypages/index'
  root 'pages#index'
  get 'pages/show'
  
  devise_for :users

  resources :baggages do
    member do
      get 'delivery_data'
      post 'toggle'
    end
  end

  resources :users #do
  #   collection do
  #     patch '/:id/user_private' => 'users#user_private'
  #   end
  # end
    namespace :admin do
      resources :baggages do
      end
    end
  
  
end

app/models/baggage.rb
class Baggage < ApplicationRecord
  belongs_to :user

  # accepts_nested_attributes_for :user

  # validates :user_id, presence: true
  validates :kind, :storage_period, :code, :user_id, presence: :true
  # validates :delivery_data

#   def user
#     #インスタンスメソッドに内で、selfはインスタンス自身をさす、baggageモデル内なのでbaggageテーブルのuser_idのこと
#     # return User.find_by(id: self.user_id)#baggageのコントローラー内でBaggageを使った定義をしているのでself部分にはそれが入るここで定義した"user"を使う
end

app/controllers/admin/baggages_controller.rb
class Admin::BaggagesController < ApplicationController
  before_action :if_not_admin, except: [:show, :delivery_data]
  before_action :set_baggage, only: [:edit, :update, :show, :destroy, :toggle]
  # before_action :move_to_index,only: [:show]
  
  def index
    
    @search = User.ransack(params[:q]) #:qは入力したクエリのq
    @users = @search.result#検索した"結果"ユーザーのparams丸ごと
    # @baggages = Baggage.find(params[:id])
    
    
    
    
    
    
  end

  def new
    # if current_user.admin?
      @baggage = Baggage.new(baggage_params)
      
    # end
  end

  def create
    
    @baggage = Baggage.new(baggage_params)
   
    if @baggage.save
      
      redirect_to baggage_path(@baggage)
    else
      
      render file: "pages/show"
     
    end
  end

  def edit
    
  end

  def update
    if @baggage.update(baggage_params)
      redirect_to baggage_path(@baggage)
    else
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if current_user.admin? && @baggage.destroy
      redirect_to root_path, notice: '削除されました'
    else
      render baggage_path
    end

  end

  def delivery_data
    # redirect_to root_path unless current_user || current_user.admin?
    @user = User.find(params[:id])
    @baggages = Baggage.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def toggle
    if @baggage.update_attributes(:delivery_data => params[:delivery_data]) # 「update_attributes」は単一の属性、今回はdelivery_dataを更新するための記述
      set_flash "update successful"
    else
      set_flash "Error, please try again"
    end
  end





  private
  

  def if_not_admin
    redirect_to root_path unless current_user.admin?#管理者ユーザー以外が特定のアクションを実行しようとした場合トップページにリダイレクトされる
  end

  def set_baggage
    @baggage = Baggage.find(params[:id])#edit, show, destroy などのアクションで使用する変数をセットします。
    
  end

  def baggage_params
    params.permit(
      :kind,:storage_period, :code, :user_id )#.merge(user_id: current_user.id)
  end

  # def delivery_data_params
  #   params.permit(
  #       :kind,:storage_period, :code, :user_id, :delivery_data )
  #   # params.require(:ba
  # end
  
  # def move_to_index
  #   redirect_to action: :index unless user_signed_in? && current_user.id == @baggage.user_id
  # end


end

app/controllers/baggages_controller.rb
class BaggagesController < ApplicationController
  before_action :if_not_admin, except: [:show, :delivery_data]
  before_action :set_baggage, only: [:edit, :update, :show, :destroy, :toggle]
  # before_action :move_to_index,only: [:show]
  
  def index
    
    @search = User.ransack(params[:q]) #:qは入力したクエリのq
    @users = @search.result#検索した"結果"ユーザーのparams丸ごと
    # @bagages = Baggage.find(user_id: @user.id)
    
  end

  def new
    # if current_user.admin?
      @baggage = Baggage.new(baggage_params)
      
  end

  def create
    
    @baggage = Baggage.new(baggage_params)
    
    if @baggage.save
      
      redirect_to baggage_path(@baggage)
    else
      
      render file: "pages/show"
      
    end
  end

  def edit
    
  end

  def update
    if @baggage.update(baggage_params)
      redirect_to baggage_path(@baggage)
    else
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if current_user.admin? && @baggage.destroy
      redirect_to user_path, notice: '削除されました'
    else
      render baggage_path
    end
  end

  def delivery_data
    # redirect_to root_path unless current_user || current_user.admin?
    @user = User.find(params[:id])
    @baggages = Baggage.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def toggle
  if @baggage.update_attributes(:delivery_data => params[:delivery_data]) # 「update_attributes」は単一の属性、今回はdelivery_dataを更新するための記述
    redirect_to delivery_data_baggage_path(@baggage)
  else
    flash.now[:alert] = 'メッセージを入力してください。'
      render :delivery_data
    
  end
end



  private
  

  def if_not_admin
    redirect_to root_path unless current_user.admin?#管理者ユーザー以外が特定のアクションを実行しようとした場合トップページにリダイレクトされる
  end

  def set_baggage
    @baggage = Baggage.find(params[:id])#edit, show, destroy などのアクションで使用する変数をセットします。
    
  end

  def baggage_params
    params.require(:baggage).permit(
      :kind,:storage_period, :code, :user_id )#.merge(user_id: current_user.id)
  end

  # def delivery_data_params
  #   params.require(:baggage).permit(
  #       :kind,:storage_period, :code, :user_id, :delivery_data )
  #   # params.require(:ba
  # end
  
  # def move_to_index
  #   redirect_to action: :index unless user_signed_in? && current_user.id == @baggage.user_id || current_user.admin
  # end


end

app/helpers/admin/baggages_helper.rb
module Admin::BaggagesHelper
end

app/helpers/baggages_helper.rb
module BaggagesHelper
end

app/views/admin/baggages/edit.html.haml
.wrapper

  .disply
    -# = form_with model: @baggage do |f|
    = form_for @baggage do |f|
      
      .baggage
        .baggage__box
          .span
            荷物の種類
            = f.select :kind, [["なまもの", "なまもの"], ["チルド", "チルド"], ["冷凍", "冷凍"], ["その他", "その他"]], include_blank: "選択して下さい"
        .baggage__box
          .span
            保管期限
            = f.text_field :storage_period, class: "baggage_text" , placeholder: '例)7'
            
        .baggage__box
          .span
            追跡番号
            = f.text_field :code, class: "baggage_text", placeholder: '123456789012'
      
      = f.hidden_field :user_id

      = f.submit 'SEND', class: "baggage__send"

app/views/admin/baggages/index.html.haml
= search_form_for @search, url: admin_baggages_url do |f| 
  = f.label :name_cont, "名前を入力してください" 
  = f.search_field :name_cont 
  = f.submit "検索" 

.table
  .thead
    %tr
      %th= sort_link(@search, :name)#resultさせてる部分とリンク
      %th= sort_link(@search, :address)
  .tbody
    - @users.each do |user|#controllerの「@users = @search.result」検索したものを"返す"
      .bar
        %td= user.name
        %td= user.address
        %td= link_to "新規",new_admin_baggage_path(user_id: user.id)
        %td= link_to "荷物一覧", delivery_data_baggage_path(user.id)#ransackは検索機能のため、deviseの登録ユーザーを探すようにuser内のindex機能が使われるため、idsと記入
        -# %td= link_to "荷物一覧", admin_baggage_url(@baggage)

  
      

app/views/admin/baggages/new.html.haml
.wrapper

  .disply
    -# = form_with model: @baggage do |f|
    = form_for @baggage do |f|
      .baggage
        .baggage__box
          .span
            荷物の種類
            = f.select :kind, [["なまもの", "なまもの"], ["チルド", "チルド"], ["冷凍", "冷凍"], ["その他", "その他"]], include_blank: "選択して下さい"
        .baggage__box
          .span
            保管期限
            = f.text_field :storage_period, class: "baggage_text" , placeholder: '例)7'
            
        .baggage__box
          .span
            追跡番号
            = f.text_field :code, class: "baggage_text", placeholder: '123456789012'
      
      = f.hidden_field :user_id

      

      = f.submit 'SEND', class: "baggage__send"

app/views/admin/baggages/show.html.haml
.wrapper
  .display
    .baggage__show
      
    .baggage__show__box
      .baggage__show__box__data
        -# - @baggage.each do |baggage|
        -#   %td= baggage.
          
      