config/routes.rb
Rails.application.routes.draw do
  
  # get 'mypages/index'
  root 'pages#index'
  get 'pages/show'
  
  devise_for :users

  resources :baggages do
    member do
      get 'delivery_data'
      post 'toggle'
    end
  end

  resources :users #do
  #   collection do
  #     patch '/:id/user_private' => 'users#user_private'
  #   end
  # end
    namespace :admin do
      resources :baggages do
      end
    end
  
  
end

app/models/baggage.rb
class Baggage < ApplicationRecord
  belongs_to :user

  # accepts_nested_attributes_for :user

  # validates :user_id, presence: true
  validates :kind, :storage_period, :code, :user_id, presence: :true
  # validates :delivery_data

#   def user
#     #インスタンスメソッドに内で、selfはインスタンス自身をさす、baggageモデル内なのでbaggageテーブルのuser_idのこと
#     # return User.find_by(id: self.user_id)#baggageのコントローラー内でBaggageを使った定義をしているのでself部分にはそれが入るここで定義した"user"を使う
end

app/controllers/admin/baggages_controller.rb
class Admin::BaggagesController < ApplicationController
  before_action :if_not_admin, except: [:show, :delivery_data]
  before_action :set_baggage, only: [:edit, :update, :show, :destroy, :toggle]
  # before_action :move_to_index,only: [:show]
  
  def index
    
    @search = User.ransack(params[:q]) #:qは入力したクエリのq
    @users = @search.result#検索した"結果"ユーザーのparams丸ごと
    # @baggages = Baggage.find(params[:id])
    
    
    
    
    
    
  end

  def new
    # if current_user.admin?
      @baggage = Baggage.new(baggage_params)
      
    # end
  end

  def create
    
    @baggage = Baggage.new(baggage_params)
   
    if @baggage.save
      
      redirect_to baggage_path(@baggage)
    else
      
      render file: "pages/show"
     
    end
  end

  def edit
    
  end

  def update
    if @baggage.update(baggage_params)
      redirect_to baggage_path(@baggage)
    else
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if current_user.admin? && @baggage.destroy
      redirect_to root_path, notice: '削除されました'
    else
      render baggage_path
    end

  end

  def delivery_data
    # redirect_to root_path unless current_user || current_user.admin?
    @user = User.find(params[:id])
    @baggages = Baggage.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def toggle
    if @baggage.update_attributes(:delivery_data => params[:delivery_data]) # 「update_attributes」は単一の属性、今回はdelivery_dataを更新するための記述
      set_flash "update successful"
    else
      set_flash "Error, please try again"
    end
  end





  private
  

  def if_not_admin
    redirect_to root_path unless current_user.admin?#管理者ユーザー以外が特定のアクションを実行しようとした場合トップページにリダイレクトされる
  end

  def set_baggage
    @baggage = Baggage.find(params[:id])#edit, show, destroy などのアクションで使用する変数をセットします。
    
  end

  def baggage_params
    params.permit(
      :kind,:storage_period, :code, :user_id )#.merge(user_id: current_user.id)
  end

  # def delivery_data_params
  #   params.permit(
  #       :kind,:storage_period, :code, :user_id, :delivery_data )
  #   # params.require(:ba
  # end
  
  # def move_to_index
  #   redirect_to action: :index unless user_signed_in? && current_user.id == @baggage.user_id
  # end


end

app/controllers/baggages_controller.rb
class BaggagesController < ApplicationController
  before_action :if_not_admin, except: [:show, :delivery_data]
  before_action :set_baggage, only: [:edit, :update, :show, :destroy, :toggle]
  # before_action :move_to_index,only: [:show]
  
  def index
    
    @search = User.ransack(params[:q]) #:qは入力したクエリのq
    @users = @search.result#検索した"結果"ユーザーのparams丸ごと
    # @bagages = Baggage.find(user_id: @user.id)
    
  end

  def new
    # if current_user.admin?
      @baggage = Baggage.new(baggage_params)
      
  end

  def create
    
    @baggage = Baggage.new(baggage_params)
    
    if @baggage.save
      
      redirect_to baggage_path(@baggage)
    else
      
      render file: "pages/show"
      
    end
  end

  def edit
    
  end

  def update
    if @baggage.update(baggage_params)
      redirect_to baggage_path(@baggage)
    else
      render :edit
    end
  end

  def show
    
  end

  def destroy
    if current_user.admin? && @baggage.destroy
      redirect_to user_path, notice: '削除されました'
    else
      render baggage_path
    end
  end

  def delivery_data
    # redirect_to root_path unless current_user || current_user.admin?
    @user = User.find(params[:id])
    @baggages = Baggage.where(user_id: @user.id).order("created_at DESC").page(params[:page]).per(5)
    
  end

  def toggle
  if @baggage.update_attributes(:delivery_data => params[:delivery_data]) # 「update_attributes」は単一の属性、今回はdelivery_dataを更新するための記述
    redirect_to delivery_data_baggage_path(@baggage)
  else
    flash.now[:alert] = 'メッセージを入力してください。'
      render :delivery_data
    
  end
end



  private
  

  def if_not_admin
    redirect_to root_path unless current_user.admin?#管理者ユーザー以外が特定のアクションを実行しようとした場合トップページにリダイレクトされる
  end

  def set_baggage
    @baggage = Baggage.find(params[:id])#edit, show, destroy などのアクションで使用する変数をセットします。
    
  end

  def baggage_params
    params.require(:baggage).permit(
      :kind,:storage_period, :code, :user_id )#.merge(user_id: current_user.id)
  end

  # def delivery_data_params
  #   params.require(:baggage).permit(
  #       :kind,:storage_period, :code, :user_id, :delivery_data )
  #   # params.require(:ba
  # end
  
  # def move_to_index
  #   redirect_to action: :index unless user_signed_in? && current_user.id == @baggage.user_id || current_user.admin
  # end


end

app/helpers/admin/baggages_helper.rb
module Admin::BaggagesHelper
end

app/helpers/baggages_helper.rb
module BaggagesHelper
end

app/views/baggages/delivery_data.html.haml
.wrappers

  .user_box
    - @baggages.each do |baggage|
      .user_box__field
        .user_box__label
          追跡番号
        .user_box__date
          = baggage.code
        .user_box__label
          到着日時
        .user_box__date
          = baggage.created_at.strftime("%Y年%m月%d日 %H時%M分")
        .user_box__label
          配達
        .user_box__date
          = baggage.delivery_data ? '出庫' : '保管中'
          

        .user_box__link
          = link_to baggage_path(baggage.id) do
            %i.fa.fa-external-link-square-alt
          
          -# <i class="fas fa-external-link-square-alt"></i>
            <i class="fas fa-cog"></i><i class="far fa-external-link"></i>
        .user_box__post
          
        - if current_user.admin?
          = check_box 'baggage', 'delivery_data',{checked: baggage[:delivery_data], class: "task-check",id: baggage.id}, true, false
          %br
            保管状況
    = paginate @baggages

app/views/baggages/show.html.haml
.wrapper
  .display
    .baggage__show
      
      .baggage__show__box
        .baggage__show__box__label
          追跡番号
        .baggage__show__box__data
          = @baggage.code
      .baggage__show__box
        .baggage__show__box__label
          種類
        .baggage__show__box__data
          = @baggage.kind
      .baggage__show__box
        .baggage__show__box__label
          保管期限
        .baggage__show__box__data
          = @baggage.storage_period
          .day
            日
      .baggage__show__box
        .baggage__show__box__label
          到着日時
        .baggage__show__box__data
          = @baggage.created_at.strftime("%Y年%m月%d日 %H時%M分")

        - if current_user.admin?
          .baggage__show__box__edit
            = link_to "編集", edit_admin_baggage_path(@baggage.id)
          .baggage__show__box__destroy
            = link_to "削除", baggage_path(@baggage), method: :delete 




          